### ISSUE TITLE
ann2rr - exception if setting the N parameter 

### ISSUE THREAD

**Issue by moeinenayati** [ikarosilva/wfdb-app-toolbox#105]
I'm trying to use the ann2rr function to load a data set from the Physionet using th efollowing command in matlab:
[rr,tm]=ann2rr('crisdb/e/e001a','atr')
and it worked properly.

But when adding the N parameter (number of records to be downloaded), got this exception:

Error using ann2rr (line 86)
Java exception occurred:
java.lang.NullPointerException

Line 63 contains this line: data=javaWfdbExec.execToDoubleArray(wfdb_argument);
and by debugging wfdb_argument is equal to:
++  working case:  '-r'    'crisdb/e/e001a'    '-a'    'atr'    '-f'    '0'    '-c'    '-V'
--   not working:     '-r'    'crisdb/e/e001a'    '-a'    'atr'    '-f'    '0'    '-t'    '9'    '-c'    '-V'

**Comment by moeinenayati** [comment]
I realized that N is time not the index (file documentation is incorrect), and if I use a big number I will get some results.

But still I need to have a filter on the number of records. 
is it possible?

**Comment by cx1111** [comment]
Actually N is the index, and the documentation is not wrong. In the code it prepends 's' to the sample number fed into the wfdb application which means sample. 

And N is not "_number of records to be downloaded_" as you stated above, it is the sample number to stop at. Therefore there is just going to be the java error that no samples are returned if you tell the function to stop at sample number N where N is smaller than the index of the first annotation.
