### ISSUE TITLE
wrsamp issue with javaWfdbExec

### ISSUE THREAD

**Issue by TenanATC** [ikarosilva/wfdb-app-toolbox#109]
Hi Ikaro,
Thanks for the great toolbox and all of the work you do on it.  I'm having issues with wrsamp.  Here is a non-reproducable example:

data = Shimmer_ECG_LARA;
Fs = 1024;
tm = [1:length(Shimmer_ECG_LARA)].';
gain = 1; %need to adjust;
format = 24; %this is correct, but maybe adjust?;

wrsamp(tm, data, 'test1', Fs, gain, format)

Which throws the following error:
<b>
No method 'setArguments' with matching signature found for class 'org.physionet.wfdb.Wfdbexec'.

Error in wrsamp (line 106)
javaWfdbExec.setArguments(wfdb_argument);
</b>

Windows 7, Matlab 2014b.  The install worked correctly and ran the demo without issue.  Any idea where the issue may reside?

**Comment by TenanATC** [comment]
I have been able to replicate this on a second Windows 7 computer running Matlab R2010a.

**Comment by cx1111** [comment]
The format is supposed to be a string. 

format = '24'

By the way, wrsamp doesn't have the ability to write baseline values. Might be better to use mat2wfdb.
