### ISSUE TITLE
wqrs problem

### ISSUE THREAD

**Issue by Qiang1991** [ikarosilva/wfdb-app-toolbox#110]
Hi Ikaro,

Thanks for the toolbox and great work you did on it. In my research, I use the fusion of "eplimited" and "wqrs" to get bSQI as a reflection of signal quality. 

However, when running with some records of the training datasets of Physionet Challenge 2015, the "wqrs.m" met some errors. the first picture shows how I use this function, and other pictures demonstrate the error. Is there any solutions to this  error?
![4](https://cloud.githubusercontent.com/assets/14898713/10355764/57b98d56-6da2-11e5-9d9a-d9d2d8b6f27e.PNG)
![0](https://cloud.githubusercontent.com/assets/14898713/10355766/57be21b8-6da2-11e5-969a-70e5280deefb.PNG)
![1](https://cloud.githubusercontent.com/assets/14898713/10355765/57be1ac4-6da2-11e5-8e16-3b2242195712.PNG)
![2](https://cloud.githubusercontent.com/assets/14898713/10355767/57c15996-6da2-11e5-94b8-7101ba0090c2.PNG)
![3](https://cloud.githubusercontent.com/assets/14898713/10355768/57ce6320-6da2-11e5-9033-4c2e0f888a87.PNG)

**Comment by cx1111** [comment]
The list of input parameters to be read in was wrong. I just made a fix. If you pull the latest changes, does it fix the error?

**Comment by cx1111** [comment]
Reopen this issue if it wasn't fixed.
