### ISSUE TITLE
wfdbdemo gives an error message

### ISSUE THREAD

**Issue by SigProcess** [ikarosilva/wfdb-app-toolbox#111]
Error using rdsamp (line 231)
Received: 9984 samples, expected: 10000

Error in wfdbdemo (line 11)
[tm,ecg]=rdsamp('mitdb/100',1,N);

**Comment by fernandoandreotti** [comment]
From my personal experience, if you are using a Windows-PC try running Matlab as admin.

**Comment by SigProcess** [comment]
Hi Fernando!
Thanks for your reply. I just downloaded the latest version of WFDB-app-toolbox from github and the issue is now resolved.
Regards.
