### ISSUE TITLE
Corresponding command for setwfdb in your tree?

### ISSUE THREAD

**Issue by sami10007** [ikarosilva/wfdb-app-toolbox#117]
Hi, 

According docs http://wfdb-matlab-toolbox.googlecode.com/svn/trunk/wfdb-swig-matlab/mcode/setwfdb.m, the command should exist. However, it does not exist in your tree (0-9-10), and not in 0-9-9 tree. I need a dbpath such that to allow many projects use my local files, and decrease load on your servers. I mostly need mitdb and other ecg signals. 

What is the corresponding command of setwfdb in your tree?

Best regards, 

Sami

**Comment by alistairewj** [comment]
I'm not sure if it exists anymore. My workaround was to use change directory as appropriate - not very elegant but worked. Perhaps someone else has a better solution.

**Comment by sami10007** [comment]
From Ikaro's answer about the ticket #120, I understand you can do it by doing `WFDB_PATH=['/Users/masi/Databases'];`. However, I am not anymore sure because my wfdb system is broken in OS X. I think Ikaro means to change the file directly. However, I would not like to do that. 

> The cleanest way to do this would be setting your WFDBPATH so that the toolbox searches your local directory first (default) and then either a PhysioNet server (any of the mirrors) or none at all.
> - - 
> You can change that variable at: https://github.com/ikarosilva/wfdb-app-toolbox/blob/master/mcode/wfdbloadlib.m See lines 45-50.

So I think setting your Database location first in WFDBPATH could be a solution. However, I have not succeeded. 

What do you think?

**Comment by ikarosilva** [comment]
Not relevant to toolbox (this is for swig matlab).
