### ISSUE TITLE
How to do `timeit(rdsamp(...))`?

### ISSUE THREAD

**Issue by sami10007** [ikarosilva/wfdb-app-toolbox#118]
Hi, 

I need to find out when the toolbox uses network access and how much. I can understand this better if I can do `timeit(rdsamp(...))`. My motivation is to use my local files of db (`physionetdb("mitdb", 1);`), and reduce load on your servers when doing `[tm1,sig]=rdsamp(strcat('mitdb/',num2str(patient)),channel); `. 

How can you timeit rdsamp?

**Comment by alistairewj** [comment]
Why not just call `tic` and `toc`?

**Comment by sami10007** [comment]
The command `tic ... toc` is inaccurate and not suitable for my environment, please see the thread http://stackoverflow.com/q/20558676/54964 about *How can I precisely profile /benchmark algorithms in MATLAB?*

I think this `timeit(rdsamp(...))` can be accomplished with anonymous functions. My pseudocode

```
f = @() rdsamp(...);
timeit(f);
```

My system is broken at the moment in OS X because initialised wrongly with the following so I have not manage to test the benchmarking. 

```
WFDB_PATH=['/Users/masi/Databases']; 
ECG=1; NBP=100; IBP=100; Resp=1; WFDBCAL=[ECG, NBP, IBP, Resp]; % TODO ask if right http://www.physionet.org/physiotools/wag/wfdbca-5.htm
debugLevel=5; networkWaitTime=1000; [isloaded,config]=wfdbloadlib(debugLevel, networkWaitTime); 
N0=1; rawUnits=1; % Physical units: base and gain already applied 
[sig, Fs, tm1]=rdsamp(strcat('mitdb/',num2str(patient)),channel,N0,rawUnits); 
```

I will let you know as soon as possible if I get the benchmarking work.

**Comment by ikarosilva** [comment]
beyond scope of the toolbox.
