### ISSUE TITLE
How to Restore wfdb without reinstallation?

### ISSUE THREAD

**Issue by sami10007** [ikarosilva/wfdb-app-toolbox#121]
I ruined my wfdb os x 10.11.4 with 0-9-10 by running wrong initialisation. I can reproduce bug #106 etc by the following

```
WFDB_PATH=['/Users/masi/Databases']; 
ECG=1; NBP=100; IBP=100; Resp=1; WFDBCAL=[ECG, NBP, IBP, Resp]; % TODO ask http://www.physionet.org/physiotools/wag/wfdbca-5.htm
debugLevel=5; networkWaitTime=1000; [isloaded,config]=wfdbloadlib(debugLevel, networkWaitTime); 
N0=1; rawUnits=1; % Physical units: base and gain already applied 
[sig, Fs, tm1]=rdsamp(strcat('mitdb/',num2str(patient)),channel,N0,rawUnits); 
```

I restarted Matlab and the OSX but I cannot get wfdb back to its default. Running the above command ruins the system in such a way that not even restart restores the settings. It would be great to understand why doing such commands make changes to the system itself. I think this should not be the case. 

---

How can you restore WFDB system?

**Comment by ikarosilva** [comment]
These commands should not change your configuration (you are just defining variables in your local workspace). Looks like your configuration was corrupted prior to this.
