### ISSUE TITLE
fwrite mat2wfdb format 80

### ISSUE THREAD

**Issue by cx1111** [ikarosilva/wfdb-app-toolbox#126]
`count=fwrite(fid,y',['int' num2str(bit_res)],skip,machine_format);`

I'm not sure if that works correctly for writing format 80 signals. y is signed 2's complement form whereas format 80 wfdb are byte offset form. Just a quick thought I'll check and close this later on.

**Comment by sami10007** [comment]
Can you please describe how you solved your case? Your output? Your expected output?
