### ISSUE TITLE
Bug in tach

### ISSUE THREAD

**Issue by opterix** [ikarosilva/wfdb-app-toolbox#128]
When using tach function, the first two measures are always equal. I tried for several signals and I got that result. It seems very odd.
Example:

> > aux=tach('a26', 'fqrs', [], [], 5) 
> > aux =
> >   139.5350*
> >   139.5350*
> >   139.0680
> >   138.8500
> > 
> > aux=tach('a27', 'fqrs', [], [], 5)
> > aux =
> >    80.0000*
> >    80.0000*
> >   133.7310
> >   133.6320
> > 
> > aux=tach('a28', 'fqrs', [], [], 5)
> > aux =
> >   172.4140*
> >   172.4140*
> >   167.5200
> >   171.1980

**Comment by cx1111** [comment]
So it's not a bug with the matlab code, it's just a result of how the c code from the original wfdb software package was written. Description: _"produces a uniformly sampled and
smoothed instantaneous heart rate signal.  Smoothing is accomplished by finding
the number of fractional R-R intervals within a window (with a width of two
output sample intervals) centered on the current output sample."_

So it's rather difficult to provide a smoothed instantaneous heart rate for the very first window given that there are no samples are time t<0. I assume it will try to estimate it based on the next window or vice versa, hence the first 2 HRs being the same.
