### ISSUE TITLE
problems with java/octave/windows

### ISSUE THREAD

**Issue by dmedine** [ikarosilva/wfdb-app-toolbox#136]
I have tried using this with jdk 8 as well as jdk 7. First of all, if you have jdk 7, you have to do a little registry editing due to this bug: https://bugs.openjdk.java.net/browse/JDK-8075410. Changing 'client' to 'server' in the appropriate place does not help however. When I run wfdbdemo from Octave I still get 

```
octave> wfdbdemo
error: javaMethod: could not find library or dependencies: C:\Program Files\Java\jre7\bin\server\jvm.dll
```

Even though the dll is clearly there. I assume I need to rebuild the jar files? I'm on 64 bit.

**Comment by dmedine** [comment]
Actually, it turned out the problem was that I was missing another detail in my path. I didn't have C:\Program Files\Java\jdk1.7.0_80\bin there

**Comment by iord** [comment]
Hello, I have the same problem but I can't understand the solution that you mention, could you please be more descriptive? Thank you!
