### ISSUE TITLE
nativelibs void of native libs

### ISSUE THREAD

**Issue by particlewizard** [ikarosilva/wfdb-app-toolbox#159]
In a previous release (wfdb-app-toolbox-0-9-10), the nativelibs folder, inside the mcode folder, had precompiled executables for e.g. Windows. Is it the intention now, that one should get and compile these separately now?

**Comment by bemoody** [comment]
You're looking at a source archive or git snapshot.  Binary packages are available at <https://physionet.org/physiotools/matlab/wfdb-app-matlab/> as well as <https://github.com/ikarosilva/wfdb-app-toolbox/releases>.
