### ISSUE TITLE
wfdb-toolbox not working with Matlab R2017b

### ISSUE THREAD

**Issue by particlewizard** [ikarosilva/wfdb-app-toolbox#160]
Tested with wfdb-app-toolbox-0-9-10 and wfdb-app-toolbox-0-10-0, on Matlab R2015b and R2017b, in all cases on same PC running Windows 10 Home.
In R2017b (not R2015b), I get the following error message when trying to call rdann (I have not tried other functions):

Error using wfdbloadlib (line 98)
Cannot load on unsupported JVM: Java 1.8.0_121-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode

Error in getWfdbClass

Error in rdann (line 103)
    javaWfdbExec=getWfdbClass('rdann');

**Comment by bemoody** [comment]
This issue was fixed in version 0.10.0.  After upgrading, you may need to exit and restart Matlab (and, of course, be sure you don't have an old version of thehe toolbox in your Matlab path somewhere.)
